# This file is split into detectors, parsers and features_selected.
# Unless you've modifying the detectors / parsers, you should only
# modify features_selected which based on those values inits the necessary
# detectors and parsers.
detectors:
  - detector:
      name: HARDENING_DETECTOR
      type: HardeningDetector
      parser_to_use: None
      features_provided:
        - ro-relocation
        - stack-protector
        - fortify-source
        - PIE
        - immediate-binding
  - detector:
      name: ASLR_DETECTOR
      type: ASLRDetector
      parser_to_use: BUILD_LOG_PARSER
      features_provided:
        - aslr_in_linking
# Parsers are sometimes used by detectors.
parsers:
  - parser:
      name: BUILD_LOG_PARSER
      type: BuildLogParser
  - parser:
      name: RULES_FLAG_PARSER
      type: RulesFlagParser

# Modify the features selected to adjust which parsers and detectors run.
# Detectors are tagged with the features they can detect, uniquely labeled if
# multiple detectors clash on provided features (see features_provided).
features_seletected:
  - ro-relocation
  - stack-protector
  - fortify-source
  - PIE
  - immediate-binding
